import test from 'node:test';
import assert from 'node:assert/strict';
import { environment,seed } from './helpers.mjs';
import { summarizeScores,statusOf,dateValue,validateFile } from '../src/domain.js';
test('60/20/20 keeps ungraded scores separate from zero and excludes drafts',() => {
  const result = summarizeScores([{ category:'coursework',published:1,max_score:10,score:5 },{ category:'coursework',published:1,max_score:30,score:15 },{ category:'coursework',published:0,max_score:100,score:0 },{ category:'midterm',published:1,max_score:40,score:20 },{ category:'final',published:1,max_score:50,score:40 }]);
  assert.equal(result.total,56); assert.equal(result.complete,true);
  assert.equal(statusOf({ score:0 }),'graded'); assert.equal(statusOf({ score:null }),'pending');
  const unfinished = summarizeScores([{ category:'coursework',published:1,max_score:10,score:null }]);
  assert.equal(unfinished.groups[0].graded,0); assert.equal(unfinished.complete,false);
  assert.equal(summarizeScores([{ category:'coursework',published:1,max_score:10,score:10 },{ category:'coursework',published:1,max_score:10,score:null }]).groups[0].weighted,30);
  assert.throws(() => dateValue('2026-02-30'));
  assert.throws(() => validateFile('bad.html','application/pdf',10));
  assert.throws(() => validateFile('big.pdf','application/pdf',10485761));
});
test('classroom API: accounts, permissions, uploads, receipts, grading and preservation',async () => {
  const fixture = environment(), originalFetch = globalThis.fetch;
  globalThis.fetch = fixture.provider;
  try {
    const { call,database,state } = fixture, f = await seed(fixture);
    assert.equal((await call('/admin/overview')).status,401);
    assert.equal((await call('/setup',{ method:'POST',headers:{ 'X-Setup-Key':'local-test-setup-secret' },body:{},origin:'https://other.test' })).status,403);
    assert.equal((await call('/setup',{ method:'POST',headers:{ 'X-Setup-Key':'local-test-setup-secret' },body:{} })).status,409);
    assert.equal((await call('/admin/overview',{ cookie:f.teacherCookie })).status,200);
    const tooLarge = await call('/admin/contact',{ method:'PUT',cookie:f.teacherCookie,headers:{ 'Content-Type':'application/json' },raw:JSON.stringify({ note:'ก'.repeat(30000) }) });
    assert.equal(tooLarge.status,413);
    let cookieA = (await call('/auth/login',{ method:'POST',body:{ username:'00123',password:'StudentFirst123' } })).cookie;
    assert.equal((await call('/overview',{ cookie:cookieA })).status,428);
    assert.equal((await call('/auth/password',{ method:'PUT',cookie:cookieA,body:{ currentPassword:'StudentFirst123',password:'StudentNew123' } })).status,200);
    assert.equal((await call('/auth/me',{ cookie:cookieA })).status,401);
    const loginA = await call('/auth/login',{ method:'POST',body:{ username:'00123',password:'StudentNew123' } }); cookieA = loginA.cookie;
    assert.match(loginA.response.headers.get('Set-Cookie'),/HttpOnly/); assert.match(loginA.response.headers.get('Set-Cookie'),/Secure/); assert.match(loginA.response.headers.get('Set-Cookie'),/Max-Age=43200/);
    let cookieB = (await call('/auth/login',{ method:'POST',body:{ username:'00456',password:'StudentFirst456' } })).cookie;
    await call('/auth/password',{ method:'PUT',cookie:cookieB,body:{ currentPassword:'StudentFirst456',password:'StudentNew456' } });
    cookieB = (await call('/auth/login',{ method:'POST',body:{ username:'00456',password:'StudentNew456' } })).cookie;
    const overviewA = (await call('/overview',{ cookie:cookieA })).data, overviewB = (await call('/overview',{ cookie:cookieB })).data;
    assert.equal(overviewA.classes.length,1); assert.equal(overviewA.classes[0].id,f.classA); assert.equal(overviewB.classes[0].id,f.classB);
    assert.ok(overviewA.items.every(i => i.class_id === f.classA)); assert.ok(!JSON.stringify(overviewA).includes('followups'));
    assert.equal((await call('/admin/overview',{ cookie:cookieA })).status,403);
    assert.equal((await call(`/files/${f.file.id}`,{ cookie:cookieB })).status,403);
    assert.equal((await call(`/files/${f.file.id}`,{ cookie:cookieA })).status,200);
    assert.equal((await call(`/files/${f.file.id}`)).status,401);
    const draft = await call('/admin/lessons',{ method:'POST',cookie:f.teacherCookie,body:{ classId:f.classA,title:'คาบที่ยังไม่เผยแพร่',date:'2026-10-02',notes:'เนื้อหาของครู',published:false } });
    assert.equal(draft.status,200);
    assert.ok(!(await call('/overview',{ cookie:cookieA })).data.lessons.some(l => l.id === draft.data.id));
    assert.equal((await call(`/assignments/${f.itemB}/submit`,{ method:'POST',cookie:cookieA,body:{ fileIds:[] } })).status,403);
    assert.equal((await call(`/assignments/${f.itemA}/submit`,{ method:'POST',cookie:cookieA,body:{ fileIds:[f.file.id] } })).status,400);
    const bytes = Buffer.from('%PDF-1.7\nStudent answer\n%%EOF');
    const headers = { 'Content-Type':'application/pdf','X-File-Name':'answer.pdf','X-File-Size':String(bytes.length) };
    state.failUpload = true;
    assert.equal((await call(`/files?itemId=${f.itemA}`,{ method:'POST',cookie:cookieA,headers,raw:bytes })).status,503);
    assert.equal(database.prepare('SELECT COUNT(*) AS count FROM sl_submissions').get().count,0);
    assert.equal(database.prepare('SELECT COUNT(*) AS count FROM sl_files WHERE owner_id=?').get(f.studentA.id).count,0);
    const uploaded = await call(`/files?itemId=${f.itemA}`,{ method:'POST',cookie:cookieA,headers,raw:bytes }); assert.equal(uploaded.status,201);
    assert.equal((await call(`/files/${uploaded.data.file.id}`,{ cookie:cookieB })).status,403);
    const simultaneous = await Promise.all(['ฉบับหนึ่ง','ฉบับสอง'].map(note => call(`/assignments/${f.itemA}/submit`,{ method:'POST',cookie:cookieA,body:{ fileIds:[uploaded.data.file.id],note } })));
    assert.ok(simultaneous.every(result => result.status === 200));
    assert.equal(simultaneous[0].data.id,simultaneous[1].data.id);
    assert.equal(database.prepare('SELECT COUNT(*) AS count FROM sl_submission_files').get().count,1);
    assert.equal((await call(`/assignments/${f.itemA}/submit`,{ method:'POST',cookie:cookieA,body:{ fileIds:[uploaded.data.file.id],note:'ส่งฉบับล่าสุดก่อนครูตรวจ' } })).status,200);
    assert.equal(database.prepare('SELECT COUNT(*) AS count FROM sl_submissions WHERE item_id=? AND user_id=?').get(f.itemA,f.studentA.id).count,1);
    const submitted = (await call('/overview',{ cookie:cookieA })).data.items.find(i => i.id === f.itemA);
    assert.equal(statusOf(submitted),'submitted'); assert.ok(submitted.submitted_at > submitted.due_at);
    assert.equal((await call('/admin/score',{ method:'PUT',cookie:f.teacherCookie,body:{ itemId:f.itemA,studentId:f.studentA.id,score:0,feedback:'ลองทบทวนอีกครั้ง' } })).status,200);
    const zero = (await call('/overview',{ cookie:cookieA })).data.items.find(i => i.id === f.itemA); assert.equal(zero.score,0); assert.equal(statusOf(zero),'graded');
    assert.equal((await call(`/assignments/${f.itemA}/submit`,{ method:'POST',cookie:cookieA,body:{ fileIds:[uploaded.data.file.id] } })).status,409);
    assert.equal((await call('/admin/reopen',{ method:'PUT',cookie:f.teacherCookie,body:{ itemId:f.itemA,studentId:f.studentA.id } })).status,200);
    assert.equal(statusOf((await call('/overview',{ cookie:cookieA })).data.items.find(i => i.id === f.itemA)),'revision');
    assert.equal((await call(`/assignments/${f.itemA}/submit`,{ method:'POST',cookie:cookieA,body:{ fileIds:[uploaded.data.file.id],note:'ฉบับแก้ไข' } })).status,200);
    for (const [itemId,score] of [[f.itemA,5],[f.activity,15],[f.midterm,20],[f.final,40]]) assert.equal((await call('/admin/score',{ method:'PUT',cookie:f.teacherCookie,body:{ itemId,studentId:f.studentA.id,score } })).status,200);
    assert.equal(summarizeScores((await call('/overview',{ cookie:cookieA })).data.items).total,56);
    assert.equal((await call('/admin/score',{ method:'PUT',cookie:f.teacherCookie,body:{ itemId:f.itemA,studentId:f.studentA.id,score:5,receivedPaper:true } })).status,200);
    assert.equal(database.prepare('SELECT COUNT(*) AS count FROM sl_submission_files').get().count,0);
    assert.ok(database.prepare('SELECT id FROM sl_files WHERE id=?').get(uploaded.data.file.id));
    assert.equal((await call('/admin/score',{ method:'PUT',cookie:f.teacherCookie,body:{ itemId:f.itemB,studentId:f.studentB.id,score:10,receivedPaper:true } })).status,200);
    assert.equal((await call('/overview',{ cookie:cookieB })).data.items[0].mode,'paper');
    assert.equal((await call('/admin/score',{ method:'PUT',cookie:f.teacherCookie,body:{ itemId:f.itemB,studentId:f.studentA.id,score:10 } })).status,400);
    assert.equal((await call('/admin/score',{ method:'PUT',cookie:f.teacherCookie,body:{ itemId:f.itemA,studentId:f.studentA.id,score:11 } })).status,400);
    assert.equal((await call('/admin/followup',{ method:'PUT',cookie:f.teacherCookie,body:{ classId:f.classA,studentId:f.studentA.id,flagged:true,note:'ตามงานกับครู' } })).status,200);
    assert.equal((await call('/admin/overview',{ cookie:f.teacherCookie })).data.followups.length,1);
    assert.ok(!JSON.stringify((await call('/overview',{ cookie:cookieA })).data).includes('ตามงานกับครู'));
    assert.equal((await call(`/admin/students/${f.studentA.id}`,{ method:'PUT',cookie:f.teacherCookie,body:{ active:false } })).status,200);
    assert.equal((await call('/auth/me',{ cookie:cookieA })).status,401);
    assert.equal((await call('/auth/login',{ method:'POST',body:{ username:'00123',password:'StudentNew123' } })).status,401);
    assert.equal(database.prepare('SELECT score FROM sl_scores WHERE item_id=? AND user_id=?').get(f.itemA,f.studentA.id).score,5);
    assert.equal((await call(`/admin/students/${f.studentA.id}`,{ method:'PUT',cookie:f.teacherCookie,body:{ active:true } })).status,200);
    cookieA = (await call('/auth/login',{ method:'POST',body:{ username:'00123',password:'StudentNew123' } })).cookie;
    assert.equal((await call('/overview',{ cookie:cookieA })).status,200);
    assert.equal((await call(`/admin/students/${f.studentA.id}/password`,{ method:'PUT',cookie:f.teacherCookie,body:{ password:'ResetStudent123' } })).status,200);
    assert.equal((await call('/auth/me',{ cookie:cookieA })).status,401);
    const reset = await call('/auth/login',{ method:'POST',body:{ username:'00123',password:'ResetStudent123' } }); assert.equal(reset.data.user.mustChange,true);
    await call('/auth/logout',{ method:'POST',cookie:reset.cookie }); assert.equal((await call('/auth/me',{ cookie:reset.cookie })).status,401);
    const connection = JSON.parse(database.prepare("SELECT value FROM sl_settings WHERE key='drive_connection'").get().value);
    assert.ok(!connection.refreshToken.includes('local-test-refresh'));
    const expiredState = await call('/admin/drive/callback?state=invalid&code=local-code',{ cookie:f.teacherCookie }); assert.equal(expiredState.status,400);
    const reconnect = await call('/admin/drive/connect',{ method:'POST',cookie:f.teacherCookie,body:{} });
    const nonce = new URL(reconnect.data.url).searchParams.get('state');
    assert.equal((await call(`/admin/drive/callback?state=${nonce}&code=local-code`,{ cookie:f.teacherCookie })).status,303);
    assert.equal((await call(`/admin/drive/callback?state=${nonce}&code=local-code`,{ cookie:f.teacherCookie })).status,400);
    database.prepare('UPDATE sl_sessions SET expires_at=0 WHERE user_id=?').run(f.teacher.id);
    assert.equal((await call('/admin/overview',{ cookie:f.teacherCookie })).status,401);
  } finally { globalThis.fetch = originalFetch; fixture.database.close(); }
});
