import { lazy, Suspense, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Plus, Pencil, Flag, BookOpen, UsersRound, ClipboardList, Settings, Check, KeyRound, UserX, UserCheck, ExternalLink, Download } from 'lucide-react';
import { useUser } from '../contexts/UserContext';
import { api, upload } from '../lib/api';
import { mathCurriculum } from '../data/curriculum';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { PageTitle, Empty, Field, Notice, Modal, Status, FileLinks, Contact, categories, classLabel, formatDate, formatDateTime, today, dueLocal, dueISO, statusOf, summarizeScores, validateFile } from '../components/ClassroomUI';
const titles = { dashboard:'ภาพรวมของคุณครู',classes:'ห้องเรียนคณิตศาสตร์',students:'รายชื่อนักเรียน',lessons:'คาบเรียนและใบงาน',work:'ติดตามงานและตรวจงาน',scores:'คะแนนของนักเรียน',followups:'นักเรียนที่ต้องติดตาม',settings:'ตั้งค่าห้องเรียน' };
const RosterImport = lazy(() => import('../components/RosterImport'));
const newPassword = () => '12345678';
function exportCSV(name, rows) {
  const encode = value => { const text = String(value ?? ''); return `"${(typeof value === 'string' && /^[=+@-]/.test(text) ? `'${text}` : text).replaceAll('"','""')}"`; };
  const url = URL.createObjectURL(new Blob(['\uFEFF' + rows.map(row => row.map(encode).join(',')).join('\r\n')], { type:'text/csv;charset=utf-8' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export default function Admin() {
  const { view = 'dashboard' } = useParams(), { user, data, reload } = useUser();
  const [classId, setClass] = useState(''), [itemId, setItem] = useState(''), [query, setQuery] = useState(''), [filter, setFilter] = useState('all'), [modal, setModal] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState(''), [driveStatus, setDriveStatus] = useState(null);
  const selectedClass = classId || data.classes.find(c => c.active)?.id || data.classes[0]?.id || '';
  const enrolled = student => data.enrollments.filter(e => e.user_id === student.id && e.active).map(e => e.class_id);
  const classroomStudents = data.users.filter(s => s.active && enrolled(s).includes(selectedClass));
  const items = data.items.filter(i => i.class_id === selectedClass && (view !== 'work' || i.accepts_submission));
  const selectedItem = items.find(i => i.id === itemId) || items[0];
  const itemFor = (item, student) => ({ ...item, ...data.submissions.find(s => s.item_id === item.id && s.user_id === student.id), ...data.scores.find(s => s.item_id === item.id && s.user_id === student.id), id: item.id });
  const studentItems = (student, classKey = selectedClass) => data.items.filter(i => i.class_id === classKey && i.published).map(i => itemFor(i, student));
  const pendingCount = (student, classKey = selectedClass) => studentItems(student, classKey).filter(i => i.accepts_submission && ['overdue','revision'].includes(statusOf(i))).length;
  const activeStudents = data.users.filter(s => s.active);
  const missingTotal = data.classes.filter(c => c.active).reduce((sum,c) => sum + activeStudents.filter(s => enrolled(s).includes(c.id)).reduce((count,s) => count + pendingCount(s,c.id),0),0);
  function open(type, row = {}) {
    setError(''); setMessage('');
    let values = {};
    if (type === 'class') values = { title:'คณิตศาสตร์พื้นฐาน',grade:'ม.4',room:'1',year:String(new Date().getFullYear() + 543),term:1,subject:'basic',active:true,...row };
    if (type === 'student') values = { username:'',name:'',password:newPassword(),...row,classIds:row.id ? enrolled(row) : selectedClass ? [selectedClass] : [] };
    if (type === 'password') values = { studentId:row.id,username:row.username,name:row.name,password:newPassword() };
    if (type === 'archive') values = { studentId:row.id,name:row.name,active:false };
    if (type === 'lesson') values = { id:row.id,classId:row.class_id || selectedClass,title:row.title || '',date:row.lesson_date || today(),notes:row.notes || '',videoUrl:row.video_url || '',published:Boolean(row.published) };
    if (type === 'item') values = { id:row.id,classId:row.class_id || selectedClass,lessonId:row.lesson_id || '',title:row.title || '',description:row.description || '',category:row.category || 'coursework',maxScore:row.max_score || 10,acceptsSubmission:row.id ? Boolean(row.accepts_submission) : true,dueAt:dueLocal(row.due_at) || `${today()}T23:59`,published:Boolean(row.published) };
    if (type === 'grade') values = { studentId:row.student.id,itemId:row.item.id,name:row.student.name,itemTitle:row.item.title,maxScore:row.item.max_score,acceptsSubmission:Boolean(row.item.accepts_submission),score:row.item.score ?? '',feedback:row.item.feedback || '',receivedPaper:false,submission:row.item.submitted_at ? row.item : null };
    if (type === 'followup') { const previous = data.followups.find(f => f.class_id === selectedClass && f.user_id === row.id); values = { classId:selectedClass,studentId:row.id,name:row.name,flagged:true,note:previous?.note || '' }; }
    setModal({ type, values });
  }
  async function save(values, files) {
    setBusy(true); setError(''); setMessage('');
    try {
      const type = modal.type;
      if (type === 'class') await api(`/admin/classes${values.id ? `/${values.id}` : ''}`, { method:values.id ? 'PUT' : 'POST',body:values });
      if (type === 'student') { await api(`/admin/students${values.id ? `/${values.id}` : ''}`, { method:values.id ? 'PUT' : 'POST',body:values }); if (!values.id) { setModal({ type:'credentials',values }); await reload(); return; } }
      if (type === 'password') { await api(`/admin/students/${values.studentId}/password`, { method:'PUT',body:{ password:values.password } }); setModal({ type:'credentials',values }); await reload(); return; }
      if (type === 'archive') await api(`/admin/students/${values.studentId}`, { method:'PUT',body:{ active:false } });
      if (type === 'lesson' || type === 'item') {
        for (const file of files) validateFile(file.name, file.type || ({ pdf:'application/pdf',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp' })[file.name.split('.').pop().toLowerCase()], file.size);
        const payload = type === 'item' ? { ...values,dueAt:values.acceptsSubmission && values.category === 'coursework' ? dueISO(values.dueAt) : null } : values;
        const result = await api(`/admin/${type === 'lesson' ? 'lessons' : 'items'}${values.id ? `/${values.id}` : ''}`, { method:values.id ? 'PUT' : 'POST',body:{ ...payload,published:files.length ? false : values.published } });
        setModal(previous => ({ ...previous, values:{ ...values,id:result.id } }));
        for (const file of files) await upload(file, type === 'lesson' ? { lessonId:result.id } : { itemId:result.id });
        if (files.length) await api(`/admin/${type === 'lesson' ? 'lessons' : 'items'}/${result.id}`, { method:'PUT',body:payload });
      }
      if (type === 'grade') await api('/admin/score', { method:'PUT',body:{ ...values,score:values.score === '' ? null : Number(values.score) } });
      if (type === 'followup') await api('/admin/followup', { method:'PUT',body:values });
      setModal(null); setMessage('บันทึกเรียบร้อยแล้ว'); await reload();
    } catch (failure) { setError(failure.message); await reload(); } finally { setBusy(false); }
  }
  async function action(path, body, success) { setError(''); setMessage(''); setBusy(true); try { await api(path, { method:'PUT',body }); setMessage(success); await reload(); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }
  const selector = <select aria-label="เลือกห้องเรียน" className="form-input mb-5 max-w-lg" value={selectedClass} onChange={event => { setClass(event.target.value); setItem(''); }}><option value="" disabled>เลือกห้องเรียน</option>{data.classes.map(c => <option key={c.id} value={c.id}>{classLabel(c)}{!c.active ? ' · ปิดห้องแล้ว' : ''}</option>)}</select>;
  const search = <input aria-label="ค้นหารายการ" className="form-input mb-5 max-w-lg" value={query} onChange={event => setQuery(event.target.value)} placeholder="ค้นหาชื่อหรือรหัสนักเรียน…" />;
  if (!titles[view]) return <Empty title="ไม่พบหน้าจัดการ"><Link to="/admin/dashboard">กลับไปภาพรวม</Link></Empty>;
  return <><PageTitle eyebrow="พื้นที่ของคุณครู" title={titles[view]} description={view === 'followups' ? 'ครูเป็นผู้เลือกนักเรียนที่ต้องติดตาม รายการและหมายเหตุแสดงเฉพาะครู' : 'ข้อมูลที่บันทึกจะตรงกันทุกอุปกรณ์'}>{[['classes','class','เพิ่มห้องเรียน'],['students','student','เพิ่มนักเรียน'],['lessons','lesson','เพิ่มคาบเรียน'],['work','item','เพิ่มงาน'],['scores','item','เพิ่มรายการคะแนน']].filter(([key]) => key === view).map(([,type,label]) => <Button key={type} onClick={() => open(type)} disabled={type !== 'class' && !data.classes.length}><Plus size={18} />{label}</Button>)}{['classes','students'].includes(view) && <Button variant="outline" onClick={() => open('import')}><UsersRound size={18} />นำเข้ารายชื่อจาก Excel</Button>}</PageTitle><Notice>{!modal && error}</Notice><Notice success>{message}</Notice>
    {view === 'dashboard' && <><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['ห้องที่เปิดอยู่',data.classes.filter(c => c.active).length,'#e3eacb'],['นักเรียน',activeStudents.length,'#e6dcf0'],['งานค้างเลยกำหนด',missingTotal,'#f4e8c7'],['รายชื่อที่ติดตาม',data.followups.filter(f => activeStudents.some(s => s.id === f.user_id)).length,'#dce7f6']].map(([label,value,color]) => <Card key={label} style={{ background:color }}><p className="text-xs text-textSecondary">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></Card>)}</div><h2 className="mb-4 mt-8 text-xl font-bold">เริ่มจัดห้องเรียน</h2><div className="grid gap-4 md:grid-cols-2">{[['/admin/classes','1. สร้างห้องเรียน','กำหนดชั้น ห้อง และภาคเรียน',BookOpen],['/admin/students','2. เพิ่มนักเรียน','สร้างบัญชีและจัดเข้าห้อง',UsersRound],['/admin/lessons','3. ลงคาบและใบงาน','เผยแพร่เนื้อหาให้เรียนย้อนหลัง',ClipboardList],['/admin/settings','4. เชื่อม Drive และ LINE','เตรียมที่เก็บไฟล์และช่องทางติดต่อ',Settings]].map(([to,title,text,Icon]) => <Link key={to} to={to}><Card className="flex items-center gap-4 hover:border-primary/30"><Icon className="shrink-0 text-primary" size={28} /><div><h3 className="font-bold">{title}</h3><p className="mt-2 text-xs leading-6 text-textSecondary">{text}</p></div></Card></Link>)}</div>{!data.drive.connected && <Card className="mt-6 bg-[#f5edda]"><p className="text-sm leading-7">ยังไม่ได้เชื่อม Google Drive สามารถสร้างห้องและรายชื่อได้ ส่วนการแนบไฟล์จะพร้อมเมื่อเชื่อม Drive</p><Link to="/admin/settings" className="mt-3 inline-block text-sm font-semibold text-primary">เปิดหน้าตั้งค่า →</Link></Card>}</>}
    {view === 'classes' && (data.classes.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.classes.map(c => <Card key={c.id}><p className="text-xs text-textSecondary">{c.grade}/{c.room} · ภาคเรียน {c.term}/{c.year}</p><h2 className="mt-3 text-xl font-bold leading-8">{c.title}</h2><p className="mt-3 text-xs text-textSecondary">{activeStudents.filter(s => enrolled(s).includes(c.id)).length} นักเรียน · {c.active ? 'เปิดห้องอยู่' : 'ปิดห้องแล้ว'}</p><Button variant="outline" className="mt-5" onClick={() => open('class',c)}><Pencil size={15} />แก้ไขห้องเรียน</Button></Card>)}</div> : <Empty title="เริ่มจากห้องเรียนแรก">สร้างห้องเรียนก่อนเพิ่มนักเรียนและลงคาบ</Empty>)}
    {view === 'students' && <>{search}<div className="mb-5 flex flex-wrap gap-2">{[['all','บัญชีที่เปิดอยู่'],['archived','บัญชีที่ปิดไว้']].map(([key,label]) => <Button key={key} variant={filter === key ? 'secondary' : 'ghost'} onClick={() => setFilter(key)}>{label}</Button>)}</div>{data.users.filter(s => (filter === 'archived' ? !s.active : s.active) && `${s.username} ${s.name}`.includes(query)).length ? <div className="table-wrap"><table className="school-table"><thead><tr><th>นักเรียน</th><th>ห้องเรียน</th><th>จัดการบัญชี</th></tr></thead><tbody>{data.users.filter(s => (filter === 'archived' ? !s.active : s.active) && `${s.username} ${s.name}`.includes(query)).map(s => <tr key={s.id}><td className="min-w-44"><strong>{s.name}</strong><p className="mt-2 text-xs text-textSecondary">{s.username}</p>{s.must_change ? <p className="mt-2 text-[10px] text-orange-800">ต้องเปลี่ยนรหัสเริ่มต้น</p> : null}</td><td className="min-w-48">{enrolled(s).map(id => { const c = data.classes.find(c => c.id === id); return <p key={id} className="mb-1 text-xs leading-6">{c ? classLabel(c) : ''}</p>; })}</td><td><div className="flex flex-wrap gap-2"><Button variant="ghost" size="sm" onClick={() => open('student',s)}><Pencil size={14} />แก้ไข</Button><Button variant="ghost" size="sm" onClick={() => open('password',s)}><KeyRound size={14} />รีเซ็ตรหัส</Button>{s.active ? <Button variant="ghost" size="sm" onClick={() => open('archive',s)}><UserX size={14} />ปิดบัญชี</Button> : <Button variant="secondary" size="sm" disabled={busy} onClick={() => action(`/admin/students/${s.id}`,{ active:true },'คืนบัญชีแล้ว นักเรียนใช้รหัสเดิมได้')}><UserCheck size={14} />คืนบัญชี</Button>}</div></td></tr>)}</tbody></table></div> : <Empty title="ไม่มีรายชื่อในรายการนี้" />}</>}
    {view === 'lessons' && <>{selector}<input aria-label="ค้นหาคาบเรียน" className="form-input mb-5" value={query} onChange={event => setQuery(event.target.value)} placeholder="ค้นหาหัวข้อคาบเรียน…" />{data.lessons.filter(l => l.class_id === selectedClass && l.title.includes(query)).length ? <div className="space-y-4">{data.lessons.filter(l => l.class_id === selectedClass && l.title.includes(query)).map(l => <Card key={l.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-textSecondary">{formatDate(l.lesson_date)} · {l.published ? 'เผยแพร่แล้ว' : 'แบบร่าง'}</p><h2 className="mt-3 text-lg font-bold">{l.title}</h2></div><Button variant="outline" onClick={() => open('lesson',l)}><Pencil size={15} />แก้ไข</Button></div><div className="mt-4"><FileLinks files={data.files.filter(f => f.lesson_id === l.id)} /></div><Link to={`/sessions/${l.id}`} className="mt-4 inline-flex min-h-10 items-center gap-2 text-xs font-semibold text-primary">ดูหน้าบทเรียน<ExternalLink size={14} /></Link></Card>)}</div> : <Empty title="ยังไม่มีคาบเรียนในห้องนี้">เพิ่มคาบพร้อมเนื้อหาและแนบใบงาน แล้วเลือกเผยแพร่</Empty>}</>}
    {['work','scores'].includes(view) && <>{selector}{items.length ? <><div className="mb-5 flex flex-wrap gap-3"><select aria-label="เลือกรายการงานหรือคะแนน" className="form-input flex-1" value={selectedItem?.id || ''} onChange={event => setItem(event.target.value)}>{items.map(i => <option key={i.id} value={i.id}>{i.title} · {categories[i.category]}{!i.published ? ' · แบบร่าง' : ''}</option>)}</select><Button variant="outline" onClick={() => open('item',selectedItem)}><Pencil size={16} />แก้ไขรายการ</Button><Button variant="outline" onClick={() => exportCSV('คะแนนนักเรียน.csv',[['รหัสนักเรียน','ชื่อ','งาน','คะแนน','คะแนนเต็ม'],...classroomStudents.map(s => [s.username,s.name,selectedItem.title,itemFor(selectedItem,s).score ?? '',selectedItem.max_score])])}><Download size={16} />CSV</Button></div><div className="mb-5 flex flex-wrap gap-2">{[['all','ทุกคน'],['missing','ยังไม่ส่ง'],['submitted','ส่งแล้ว']].map(([key,label]) => <Button key={key} variant={filter === key ? 'secondary' : 'ghost'} onClick={() => setFilter(key)}>{label}</Button>)}</div><FileLinks files={data.files.filter(f => f.item_id === selectedItem.id && f.owner_id === user.id)} /><div className="table-wrap mt-5"><table className="school-table"><thead><tr><th>นักเรียน</th><th>งาน / คะแนน</th><th>จัดการ</th></tr></thead><tbody>{classroomStudents.filter(s => { const item = itemFor(selectedItem,s); return filter === 'all' || (filter === 'missing' ? selectedItem.accepts_submission && ['pending','overdue','revision'].includes(statusOf(item)) : Boolean(item.submitted_at) && !item.reopened); }).map(s => {
      const item = itemFor(selectedItem,s), submission = data.submissions.find(sub => sub.item_id === item.id && sub.user_id === s.id);
      return <tr key={s.id}><td className="min-w-40"><strong>{s.name}</strong><p className="mt-2 text-xs text-textSecondary">{s.username}</p></td><td className="min-w-64">{item.accepts_submission && <Status status={statusOf(item)} late={item.submitted_at && item.due_at && item.submitted_at > item.due_at} />}<p className="mt-3 text-sm">{item.score === undefined ? 'ยังไม่มีคะแนน' : `${item.score} / ${item.max_score}`}</p>{submission && <><p className="my-3 text-xs text-textSecondary">{submission.mode === 'paper' ? 'รับกระดาษ' : 'ออนไลน์'} · {formatDateTime(submission.submitted_at)}</p>{submission.mode === 'online' && <FileLinks files={data.files.filter(f => f.owner_id === s.id && f.submission_id === submission.id)} />}{submission.note && <p className="mt-2 whitespace-pre-wrap text-xs leading-6">{submission.note}</p>}</>}</td><td className="min-w-44"><Button size="sm" onClick={() => open('grade',{ student:s,item })}>รับงาน / ให้คะแนน</Button>{submission && <Button variant="ghost" className="mt-2" size="sm" disabled={busy} onClick={() => action('/admin/reopen',{ itemId:item.id,studentId:s.id },'เปิดรับแก้ไขแล้ว คะแนนเดิมถูกล้างเพื่อรอตรวจใหม่')}>เปิดรับแก้ไข</Button>}</td></tr>;
    })}</tbody></table></div>{!classroomStudents.length && <Empty title="ยังไม่มีนักเรียนในห้องนี้" />}</> : <Empty title="ยังไม่มีรายการในห้องนี้">เพิ่มงาน กิจกรรม หรือคะแนนสอบก่อนกรอกคะแนน</Empty>}</>}
    {view === 'followups' && <>{selector}<div className="mb-5 flex flex-wrap gap-2">{[['all','ทุกคน'],['risk','ครูเลือกติดตาม'],['missing','มีงานค้าง']].map(([key,label]) => <Button key={key} variant={filter === key ? 'secondary' : 'ghost'} onClick={() => setFilter(key)}>{label}</Button>)}</div>{classroomStudents.length ? <div className="grid gap-4 md:grid-cols-2">{classroomStudents.filter(s => filter === 'all' || (filter === 'risk' ? data.followups.some(f => f.user_id === s.id && f.class_id === selectedClass) : pendingCount(s) > 0)).map(s => { const flag = data.followups.find(f => f.user_id === s.id && f.class_id === selectedClass), summary = summarizeScores(studentItems(s)), hasScore = summary.groups.some(g => g.graded); return <Card key={s.id} className={flag ? 'border-orange-300 bg-[#fff8e8]' : ''}><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{s.name}</h2><p className="mt-2 text-xs text-textSecondary">{s.username}</p></div>{flag && <Flag size={20} className="shrink-0 text-orange-800" />}</div><p className="mt-4 text-sm">งานค้างเลยกำหนด / รอแก้ไข <strong>{pendingCount(s)}</strong> งาน</p><p className="mt-3 text-sm">คะแนนรวมปัจจุบัน <strong>{hasScore ? `${summary.total.toFixed(2)} / 100` : 'ยังไม่มีคะแนน'}</strong></p>{flag && <p className="mt-4 whitespace-pre-wrap text-xs leading-7 text-orange-900">ครูระบุให้ติดตาม: {flag.note || 'ยังไม่ได้เพิ่มหมายเหตุ'}</p>}<Button variant={flag ? 'outline' : 'secondary'} className="mt-5" onClick={() => open('followup',s)}><Flag size={15} />{flag ? 'แก้ไข / ยกเลิกติดตาม' : 'ระบุให้ติดตาม'}</Button></Card>; })}</div> : <Empty title="ยังไม่มีนักเรียนในห้องนี้" />}</>}
    {view === 'settings' && <div className="grid gap-5 lg:grid-cols-2"><ContactSettings user={user} contact={data.contact} onSaved={reload} /><Card><h2 className="text-xl font-bold">Google Drive ของครู</h2><p className="mt-4 text-sm leading-8 text-textSecondary">ไฟล์อยู่ในโฟลเดอร์ Sabai Learn แยกตามห้องเรียน นักเรียนเปิดไฟล์ผ่านเว็บตามสิทธิ์ของตน</p><p className="mt-4 text-sm font-semibold">{data.drive.connected ? `เชื่อมแล้ว · ${data.drive.ownerName}` : 'ยังไม่ได้เชื่อมบัญชี'}</p>{!data.drive.configured && <p className="mt-4 rounded-xl bg-[#f5edda] p-4 text-xs leading-7">ต้องตั้งค่าการเชื่อมต่อครั้งแรกตามคู่มือของเว็บก่อน แล้วครูจึงกดเชื่อมบัญชี Google ได้</p>}<div className="mt-5 flex flex-wrap gap-3"><Button disabled={busy || !data.drive.configured} onClick={async () => { setBusy(true); setError(''); try { window.location.assign((await api('/admin/drive/connect',{ method:'POST',body:{} })).url); } catch (failure) { setError(failure.message); setBusy(false); } }}>เชื่อม Google Drive</Button>{data.drive.connected && <Button variant="outline" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { setDriveStatus(await api('/admin/drive/status')); setMessage('ตรวจการเชื่อม Drive สำเร็จ'); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }}>ตรวจการเชื่อมต่อ</Button>}</div>{driveStatus?.quota && <p className="mt-5 text-xs leading-7 text-textSecondary">ใช้พื้นที่ {(Number(driveStatus.quota.usage || 0)/1e9).toFixed(2)} GB {driveStatus.quota.limit ? `จาก ${(Number(driveStatus.quota.limit)/1e9).toFixed(2)} GB` : ''}</p>}<p className="mt-5 text-xs leading-7 text-textSecondary">หากต้องเชื่อมใหม่ ใช้บัญชี Google เดิมเพื่อเปิดไฟล์ที่เก็บไว้ ไม่ต้องเปิดแชร์ไฟล์เป็นสาธารณะ</p></Card></div>}
    {modal && <Modal busy={busy} title={{ class:'ห้องเรียน',student:modal.values.id ? 'แก้ไขนักเรียน' : 'เพิ่มบัญชีนักเรียน',password:'รีเซ็ตรหัสผ่าน',archive:'ปิดบัญชีนักเรียน',lesson:'คาบเรียนและเอกสาร',item:'งานและรายการคะแนน',grade:'รับงานและบันทึกคะแนน',followup:'ติดตามนักเรียน',import:'นำเข้ารายชื่อและสร้างห้องเรียน',credentials:'บัญชีพร้อมใช้งาน' }[modal.type]} onClose={() => { if (!busy) { setModal(null); setError(''); } }}>{modal.type === 'import' ? <Suspense fallback={<p role="status">กำลังเปิดตัวนำเข้า Excel…</p>}><RosterImport data={data} onBusy={setBusy} onSaved={reload} /></Suspense> : <AdminForm key={`${modal.type}:${modal.values.id || ''}`} modal={modal} data={data} busy={busy} error={error} onSave={save} onClose={() => setModal(null)} />}</Modal>}
  </>;
}
function ContactSettings({ user, contact, onSaved }) {
  const [values,setValues] = useState(contact || { teacherName:user.name,lineUrl:'',contactHours:'วันจันทร์–ศุกร์ 08:30–16:30 น.' }), [error,setError] = useState(''), [message,setMessage] = useState(''), [busy,setBusy] = useState(false);
  return <Card><h2 className="text-xl font-bold">ช่องทางติดต่อครู</h2><Notice>{error}</Notice><Notice success>{message}</Notice><form className="mt-5 space-y-4" onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await api('/admin/contact',{ method:'PUT',body:values }); setMessage('บันทึกช่องทางติดต่อแล้ว'); await onSaved(); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }}>{[['teacherName','ชื่อครู'],['lineUrl','ลิงก์ LINE'],['contactHours','เวลาติดต่อ']].map(([key,label]) => <Field key={key} label={label}><input type={key === 'lineUrl' ? 'url' : 'text'} required={key === 'teacherName'} className="form-input" value={values[key]} onChange={event => setValues({ ...values,[key]:event.target.value })} /></Field>)}<Button type="submit" disabled={busy}>บันทึกช่องทางติดต่อ</Button></form><div className="mt-5"><Contact contact={contact} /></div></Card>;
}
function AdminForm({ modal, data, busy, error, onSave, onClose }) {
  const { type } = modal, [v,setValues] = useState(modal.values), [files,setFiles] = useState([]), [localError,setLocalError] = useState('');
  const change = (key,value) => setValues(previous => ({ ...previous,[key]:value }));
  const input = (key,label,inputType = 'text',required = true,extra = {}) => <Field label={label}><input type={inputType} required={required} className="form-input" value={v[key] ?? ''} onChange={event => change(key,event.target.value)} {...extra} /></Field>;
  const check = (key,label) => <label className="flex items-center gap-3 rounded-xl bg-background p-3 text-sm"><input type="checkbox" checked={Boolean(v[key])} onChange={event => change(key,event.target.checked)} className="h-4 w-4 shrink-0" />{label}</label>;
  const classroom = <Field label="ห้องเรียน"><select required className="form-input" value={v.classId || ''} onChange={event => { change('classId',event.target.value); change('lessonId',''); }}><option value="">เลือกห้องเรียน</option>{data.classes.map(c => <option key={c.id} value={c.id}>{classLabel(c)}</option>)}</select></Field>;
  if (type === 'credentials') return <div className="space-y-4"><Notice success>ส่งรหัสนี้ให้นักเรียนเป็นส่วนตัว นักเรียนต้องเปลี่ยนรหัสเมื่อเข้าใช้ครั้งแรก</Notice><Field label="ชื่อเข้าใช้"><input readOnly className="form-input" value={v.username} /></Field><Field label="รหัสผ่านเริ่มต้น"><input readOnly className="form-input" value={v.password} /></Field><p className="text-xs leading-7 text-textSecondary">รหัสผ่านนี้แสดงในหน้าต่างนี้เท่านั้น จดหรือคัดลอกก่อนปิด</p><Button onClick={onClose}>บันทึกรหัสไว้แล้ว</Button></div>;
  return <form className="space-y-4" onSubmit={event => { event.preventDefault(); setLocalError(''); try { if (['lesson','item'].includes(type) && !v.classId) throw new Error('เลือกห้องเรียนก่อน'); onSave(v,files); } catch (failure) { setLocalError(failure.message); } }}><Notice>{error || localError}</Notice><fieldset disabled={busy} className="space-y-4">
    {type === 'class' && <>{input('title','ชื่อรายวิชาคณิตศาสตร์')}<div className="grid grid-cols-2 gap-4">{input('grade','ระดับชั้น')}{input('room','ห้อง')}{input('year','ปีการศึกษา')}<Field label="ภาคเรียน"><select className="form-input" value={v.term} onChange={event => change('term',Number(event.target.value))}><option value={1}>1</option><option value={2}>2</option></select></Field></div><Field label="ประเภทรายวิชา"><select className="form-input" value={v.subject} onChange={event => change('subject',event.target.value)}><option value="basic">คณิตศาสตร์พื้นฐาน</option><option value="additional">คณิตศาสตร์เพิ่มเติม</option></select></Field>{check('active','เปิดห้องให้นักเรียนเข้าใช้')}<p className="text-xs leading-7 text-textSecondary">ภาคเรียนใหม่ให้สร้างห้องใหม่ เพื่อเก็บคะแนนและประวัติของภาคเดิม</p></>}
    {type === 'student' && <>{!v.id && input('username','รหัสนักเรียน','text',true,{ maxLength:40,pattern:'[a-zA-Z0-9_-]+',autoComplete:'off' })}{input('name','ชื่อ–นามสกุล')}{!v.id && input('password','รหัสผ่านเริ่มต้น','text',true,{ minLength:8,maxLength:128,autoComplete:'off' })}<Field label="ห้องเรียนที่ลงทะเบียน"><span className="grid max-h-60 gap-2 overflow-y-auto rounded-xl border border-primary/15 p-3">{data.classes.map(c => <span key={c.id} className="flex items-center gap-3 text-xs font-normal leading-6"><input type="checkbox" aria-label={classLabel(c)} checked={v.classIds.includes(c.id)} onChange={event => change('classIds',event.target.checked ? [...v.classIds,c.id] : v.classIds.filter(id => id !== c.id))} />{classLabel(c)}</span>)}</span></Field><p className="text-xs leading-7 text-textSecondary">เก็บรหัสนักเรียนเป็นข้อความ เลขศูนย์นำหน้าจะไม่หาย</p></>}
    {type === 'password' && <><p className="text-sm">{v.name} · {v.username}</p>{input('password','รหัสผ่านเริ่มต้นใหม่','text',true,{ minLength:8,maxLength:128,autoComplete:'off' })}<p className="text-xs leading-7 text-textSecondary">นักเรียนจะต้องเข้าสู่ระบบใหม่และเปลี่ยนรหัสผ่านนี้</p></>}
    {type === 'archive' && <p className="text-sm leading-8">ปิดบัญชีของ <strong>{v.name}</strong> นักเรียนจะเข้าใช้ไม่ได้ ประวัติงานและคะแนนยังอยู่ ครูคืนบัญชีได้จากรายการบัญชีที่ปิดไว้</p>}
    {['lesson','item'].includes(type) && <>{classroom}{input('title',type === 'lesson' ? 'หัวข้อคาบเรียน' : 'ชื่องาน / กิจกรรม / สอบ')}{type === 'lesson' ? <>{input('date','วันที่เรียน','date')}<Field label="เริ่มจากโครงร่างบทเรียนเดิม"><select className="form-input" defaultValue="" onChange={event => { const c = Object.values(mathCurriculum).flatMap(grade => Object.values(grade).flat()).find(c => c.id === event.target.value); if (c) setValues(previous => ({ ...previous,title:c.title,notes:`${c.description}\n\n${c.topics.map(t => t.name).join('\n')}` })); }}><option value="">เลือกแม่แบบคณิตศาสตร์ (ไม่บังคับ)</option>{Object.entries(mathCurriculum).flatMap(([grade,groups]) => Object.values(groups).flat().map(c => <option key={c.id} value={c.id}>{grade.toUpperCase()} · {c.title}</option>))}</select></Field><Field label="เนื้อหาคาบเรียน" hint="แม่แบบเป็นโครงร่าง เติมเนื้อหาของคาบจริงก่อนเผยแพร่"><textarea className="form-input min-h-48" value={v.notes} onChange={event => change('notes',event.target.value)} maxLength={20000} /></Field>{input('videoUrl','ลิงก์วิดีโอ เช่น YouTube','url',false)}</> : <><Field label="หมวดคะแนน"><select className="form-input" value={v.category} onChange={event => { change('category',event.target.value); if (event.target.value !== 'coursework') change('acceptsSubmission',false); }}>{Object.entries(categories).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field>{input('maxScore','คะแนนเต็มรายการนี้','number',true,{ min:0.01,max:100000,step:'any' })}<Field label="คาบเรียนที่เกี่ยวข้อง"><select className="form-input" value={v.lessonId} onChange={event => change('lessonId',event.target.value)}><option value="">ไม่ผูกกับคาบเรียน</option>{data.lessons.filter(l => l.class_id === v.classId).map(l => <option key={l.id} value={l.id}>{formatDate(l.lesson_date)} · {l.title}</option>)}</select></Field><Field label="คำสั่งงาน / รายละเอียด"><textarea className="form-input" value={v.description} onChange={event => change('description',event.target.value)} maxLength={10000} /></Field>{v.category === 'coursework' && check('acceptsSubmission','รายการนี้ให้นักเรียนส่งงาน')}{v.acceptsSubmission && v.category === 'coursework' && input('dueAt','กำหนดส่ง (เวลาประเทศไทย)','datetime-local')}</>}{check('published','เผยแพร่ให้นักเรียนเห็น')}<Field label="แนบใบงานหรือเอกสารใหม่" hint="PDF, DOC, DOCX, JPG, PNG หรือ WebP ไม่เกิน 10 MB ต่อไฟล์ หากแนบไม่ครบจะเก็บรายการเป็นแบบร่าง"><input type="file" multiple accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp" className="form-input" onChange={event => setFiles(Array.from(event.target.files))} /></Field>{v.id && <FileLinks files={data.files.filter(f => type === 'lesson' ? f.lesson_id === v.id : f.item_id === v.id && data.users.every(s => s.id !== f.owner_id))} />}</>}
    {type === 'grade' && <><p className="text-sm font-semibold">{v.name} · {v.itemTitle}</p>{input('score',`คะแนน (เต็ม ${v.maxScore})`,'number',false,{ min:0,max:v.maxScore,step:'any' })}<p className="text-xs leading-7 text-textSecondary">เว้นว่างเพื่อยังไม่ให้คะแนน หรือเพื่อล้างคะแนนเดิม กรอก 0 เมื่อให้ศูนย์คะแนน</p>{v.acceptsSubmission && check('receivedPaper','ครูได้รับงานกระดาษแล้ว')}<Field label="ข้อเสนอแนะถึงนักเรียน"><textarea className="form-input" value={v.feedback} onChange={event => change('feedback',event.target.value)} maxLength={2000} /></Field></>}
    {type === 'followup' && <><p className="font-semibold">{v.name}</p>{check('flagged','ระบุให้อยู่ในรายชื่อนักเรียนที่ต้องติดตาม')}<Field label="เหตุผล / แนวทางช่วยเหลือ (ครูเห็นเท่านั้น)"><textarea className="form-input" value={v.note} onChange={event => change('note',event.target.value)} maxLength={2000} /></Field></>}
    <Button type="submit" disabled={busy} className="w-full"><Check size={17} />{busy ? 'กำลังบันทึก…' : type === 'archive' ? 'ปิดบัญชีและเก็บประวัติ' : 'บันทึก'}</Button>
  </fieldset></form>;
}
