import { useState } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, ArrowRight, Search, UserRound, Star, PlayCircle, FileText, GraduationCap } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { ProgressBar } from '../components/ui/ProgressBar';
import { TabSwitcher } from '../components/ui/TabSwitcher';
import { useUser } from '../contexts/UserContext';
import { mathCurriculum } from '../data/curriculum';
import { getDashboardCourses } from '../data/platform';

export default function Course() {
  const { currentGrade, getGradeLabel } = useUser();
  const [category, setCategory] = useState('all');
  const [activeType, setActiveType] = useState('basic');
  const [query, setQuery] = useState('');
  const chapters = mathCurriculum[currentGrade][activeType].filter(chapter => chapter.title.toLowerCase().includes(query.trim().toLowerCase()));
  const courses = getDashboardCourses(currentGrade).filter(course => (!query.trim() || course.title.toLowerCase().includes(query.trim().toLowerCase())) && (category === 'all' || (category === 'science' ? course.id === 'physics' : ['thai', 'english'].includes(course.id))));
  const categories = [{ id: 'all', label: 'รายวิชาทั้งหมด' }, { id: 'math', label: 'คณิตศาสตร์' }, { id: 'science', label: 'วิทยาศาสตร์' }, { id: 'language', label: 'ภาษา' }];

  return (
    <div className="space-y-7">
      <section className="greeting-banner flex flex-wrap items-center justify-between gap-5 rounded-2xl p-6 md:p-8"><div><p className="mb-2 flex items-center gap-2 text-xs font-medium text-primary"><GraduationCap size={18} />ห้องเรียนของคุณ · {getGradeLabel()}</p><h1 className="text-2xl font-bold">วิชาของฉัน <span className="font-normal text-primary">(My Courses)</span></h1><p className="mt-2 text-sm text-textSecondary">เรียนรู้สิ่งใหม่ ทบทวนสิ่งที่คุ้นเคย และเติบโตในทุก ๆ วัน</p></div><span className="rounded-2xl bg-white/80 px-5 py-4 text-center"><span className="block text-2xl font-bold text-primary">4</span><span className="text-xs text-textSecondary">รายวิชาในภาคเรียนนี้</span></span></section>
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex flex-wrap gap-2" aria-label="หมวดหมู่รายวิชา">{categories.map(item => <button key={item.id} onClick={() => setCategory(item.id)} aria-pressed={category === item.id} className={`rounded-full px-4 py-2.5 text-xs font-medium transition-colors ${category === item.id ? 'bg-secondary text-primary' : 'bg-white text-textSecondary hover:bg-secondary/40'}`}>{item.label}</button>)}</div><div className="relative"><Search className="absolute left-3.5 top-3 text-textSecondary" size={16} /><input aria-label="ค้นหารายวิชา" value={query} onChange={event => setQuery(event.target.value)} placeholder="ค้นหารายวิชา..." className="h-10 w-full rounded-xl border border-[#e8e9e1] bg-white pl-10 pr-4 text-xs outline-none focus:border-success md:w-56" /></div></div>
      {category === 'math' ? <><TabSwitcher activeType={activeType} onTypeChange={setActiveType} /><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{chapters.map(chapter => <Card key={chapter.id} className="flex flex-col p-6"><div className="mb-5 flex items-center justify-between"><span className="rounded-xl bg-secondary/50 p-3 text-primary"><BookOpen size={23} /></span><span className="text-xs text-textSecondary">{chapter.chapter}</span></div><h2 className="text-lg font-bold">{chapter.title}</h2><p className="mt-2 line-clamp-2 min-h-11 text-xs leading-relaxed text-textSecondary">{chapter.description}</p><div className="mt-5 flex justify-between text-[11px]"><span>ความคืบหน้า</span><span className="text-primary">{chapter.progress}%</span></div><ProgressBar value={chapter.progress} className="mt-2 h-2" indicatorColor="bg-success" /><div className="mt-5 flex gap-4 text-xs text-textSecondary"><span className="flex items-center gap-1.5"><PlayCircle size={14} />{chapter.topics.reduce((count, topic) => count + topic.videos.length, 0)} คลิป</span><span className="flex items-center gap-1.5"><FileText size={14} />{chapter.documents.length} เอกสาร</span></div><Link to={`/courses/${chapter.id}`} className="mt-6 flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary text-xs font-semibold text-white hover:bg-[#30593b]">เข้าสู่บทเรียน <ArrowRight size={16} /></Link></Card>)}</div>{!chapters.length && <Empty />}</> : <><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{courses.map(course => <Card key={course.id} className="flex flex-col p-6"><div className="mb-5 flex items-center justify-between"><span className="rounded-full bg-[#f4f2ee] px-3 py-1.5 text-[10px] text-textSecondary">{course.tag}</span><span className="flex items-center gap-1 text-xs text-primary"><Star size={14} />{course.score}</span></div><h2 className="min-h-14 text-lg font-bold">{course.title}</h2><p className="mt-1 flex items-center gap-1.5 text-xs text-textSecondary"><UserRound size={14} />{course.teacher}</p><div className="mt-7 flex justify-between text-[11px]"><span>ความคืบหน้า</span><span className="font-medium text-primary">{course.completed}/{course.lessons} บท ({course.progress}%)</span></div><ProgressBar value={course.progress} className="mt-2 h-2" indicatorColor="bg-success" /><Link to={course.id.startsWith('m') ? '/courses?category=math' : course.to} onClick={course.id.startsWith('m') ? event => { event.preventDefault(); setCategory('math'); setActiveType('additional'); setQuery(''); } : undefined} className="mt-6 flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary text-xs font-semibold text-white hover:bg-[#30593b]">{course.progress === 100 ? 'ทบทวนรายวิชา' : 'เข้าสู่รายวิชา'} <ArrowRight size={16} /></Link></Card>)}</div>{!courses.length && <Empty />}</>}
      <div className="flex items-center gap-3 rounded-2xl bg-[#f0f4eb] px-5 py-4 text-xs leading-relaxed text-[#75836e]"><BookOpen className="shrink-0 text-primary" size={20} />เนื้อหาคณิตศาสตร์มีทั้งวิชาพื้นฐานและเพิ่มเติม สำหรับชั้น ม.4–ม.6 เลือกระดับชั้นได้จากเมนูด้านบน</div>
    </div>
  );
}

function Empty() { return <div className="py-16 text-center text-sm text-textSecondary"><Search className="mx-auto mb-3 text-success" size={30} />ไม่พบรายวิชา ลองเปลี่ยนหมวดหมู่หรือคำค้น</div>; }
